### PR TITLE
Require filter_spam in lib instead of in model

### PR DESCRIPTION
**Pull request by bricesanchez**
I'm doing the same of RefineryCMS Blog and it looks cleaner : 
https://github.com/refinery/refinerycms-blog/search?utf8=%E2%9C%93&q=filters_spam

### CODE REVIEW

**Comment by bricesanchez** [comment]
@simi, @parndt is it ok for you ?

**Comment by parndt** [comment]
Is this just cosmetic? Shouldn't a library be required where it's used?

**Comment by bricesanchez** [comment]
It's just cosmetic. So what is the best practice? Inquiries or Blog ?

**Comment by parndt** [comment]
I think that requiring it when it's used is best, so that we don't bloat the ObjectSpace immediately upon the extension being loaded, but rather when it's needed.

**Pull request closed without merging**
