### PR TITLE
Feature/recaptcha support

### PR DESCRIPTION
**Pull request by bricesanchez**
I create this PR for you @parndt, i need this feature for a client :)

### CODE REVIEW

**Comment by bricesanchez** [comment]
http://localhost:3000/refinery/inquiries returns an error if we activate Recaptcha : 

```ruby
undefined method `ham' for #<Class:0x007fd701107900>

Extracted source (around line #26):
24
25
26
27
28
29
              
        send(name, *arguments, &block)
      else
        super
      end
    end


Rails.root: /Users/bci20/Sites/refinery/refinerycms-inquiries/spec/dummy

Application Trace | Framework Trace | Full Trace
activerecord (4.2.6) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/Users/bci20/Sites/refinery/refinerycms-inquiries/app/controllers/refinery/inquiries/admin/inquiries_controller.rb:36:in `find_all_ham'
```

**Comment by bricesanchez** [comment]
i think we shoud a `ham` and `spam` scopes in `Inquiry` model to be backward compatible : 

```git
diff --git a/app/models/refinery/inquiries/inquiry.rb b/app/models/refinery/inquiries/inquiry.rb
index 0bac718..11dac12 100644
--- a/app/models/refinery/inquiries/inquiry.rb
+++ b/app/models/refinery/inquiries/inquiry.rb
@@ -21,6 +21,9 @@ module Refinery

       default_scope { order('created_at DESC') }

+      scope :ham, -> { where(spam: false) }
+      scope :spam, -> { where(spam: true) }
+
       def self.latest(number = 7, include_spam = false)
         include_spam ? limit(number) : ham.limit(number)
       end
```

**Comment by parndt** [comment]
Can you add that commit to the branch?

**Comment by bricesanchez** [comment]
done :)

**Comment by parndt** [comment]
@bricesanchez is this working for you in your application?

**Comment by bricesanchez** [comment]
Yep

**Pull request merged**
