### PR TITLE
Add support for refinerycms-core 4.0

### PR DESCRIPTION
**Pull request by bricesanchez**
Note: Specs will not fail after the release of refinerycms-settings for 4.0

### CODE REVIEW

**Comment by bricesanchez** [comment]
@parndt it's ready to be merged and released

**Comment by markquezada** [comment]
@bricesanchez @parndt Hey guys, just wondering if there's a reason why this was never released?

**Comment by bricesanchez** [comment]
I think @parndt forgot to release it :D

**Comment by parndt** [comment]
🤦‍♂️

**Pull request merged**
